#AUTOGENERATED! DO NOT EDIT! File to edit: dev/01_data.ipynb (unless otherwise specified).

__all__ = ['download_file', 'get_files', 'num_files']

#Cell
from ..imports import *

#Cell
def download_file(url, dest):
    if os.path.exists(dest): raise Exception(f"path {dest} already exists.")
    s = requests.Session()
    u = s.get(url, stream=True)
    with open(dest, "wb") as f:
        nbytes = 0
        for chunk in u.iter_content(chunk_size=1024*1024):
            nbytes += len(chunk)
            f.write(chunk)

#Cell
def get_files(path):
    "return a list of file names present in `path`"
    return [o.name for o in os.scandir(path)]

#Cell
def num_files(path):
    "return number of files in `path`"
    return len(os.listdir(path))