#AUTOGENERATED! DO NOT EDIT! File to edit: dev/02_preprocess.ipynb (unless otherwise specified).

__all__ = ['path', 'trn_sample', 'tst_sample']

#Cell
from ..imports import *
from .core import *

#Cell
path = Path("/home/ubuntu/repos/FakeDetector/")
trn_sample = path/"train_sample_videos/"
tst_sample = path/"test_videos/"