#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_file": "01_data.ipynb",
         "get_files": "01_data.ipynb",
         "num_files": "01_data.ipynb",
         "path": "02_preprocess.ipynb",
         "trn_sample": "02_preprocess.ipynb",
         "tst_sample": "02_preprocess.ipynb"}

modules = ["data/core.py",
           "data/preprocess.py"]

git_url = "https://github.com/amaarora/face_detector/tree/master/"

def custom_doc_links(name): return None