#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["imports.py"]

git_url = "https://github.com/amaarora/face_detector/tree/master/"

def custom_doc_links(name): return None